{
 "title": "SRC Dash",
 "time": { "from": "now-300m", "to": "now-290m" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SRC Vehicle Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "src_vehicle_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SRC Vehicle Acceleration ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "src_vehicle_accel", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SRC Battery Voltage Gauge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "src_battery_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SRC Battery Temperature Gauge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "src_battery_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SRC Vehicle Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "src_vehicle_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SRC Vehicle Acceleration ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "src_vehicle_accel", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SRC Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "src_battery_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SRC Battery Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "src_battery_temp", "legendFormat": "__auto" }
   ]
  }
 ]
}